version: 2

models:
  - name: stg_localbike_production_database__brands
    description: "This model contains product brands referential"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null


  - name: stg_localbike_production_database__categories
    description: "This model contains product categories referential"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
            - unique
            - not_null


  - name: stg_localbike_production_database__products
    description: "This model contains details of products available for sale"
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the product brand referential."
        tests:
          - relationships:
              name: brand_id_id_foreign_key_in_stg_localbike_production_database__product
              to: ref('stg_localbike_production_database__brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product category referential."
        tests:
          - relationships:
              name: category_id_id_foreign_key_in_stg_localbike_production_database__product
              to: ref('stg_localbike_production_database__categories')
              field: brand_id


  - name: stg_localbike_production_database__stocks
    description: "This model contains information about products stocks for each store"
    columns:
      - name: stock_id
        description: "Primary key, unique identifier: generated by concatenating store_id and product_id."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the store."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_localbike_production_database__stocks
              to: ref('stg_localbike_sales_database__stores')
              field: store_id
      - name: product_id
        description: "Foreign key linking the product items."
        tests:
          - relationships:
              name: product_id_id_foreign_key_in_stg_localbike_production_database__stocks
              to: ref('stg_localbike_production_database__products')
              field: product_id

 