version: 2

sources:
  - name: localbike_production_database
    schema: localbike_production_database
    tables:
      - name: brands
      - name: categories
      - name: products
      - name: stocks

  - name: localbike_sales_database
    schema: localbike_sales_database
    tables:
      - name: customers
      - name: order_items
      - name: orders
      - name: staffs
      - name: stores


